/**
 * Kael Agent Runtime with OpenClaw Integration
 * Implements the planning loop with LLM-driven tool selection
 */

import { z } from 'zod';
import { logger } from '../logger/index.js';
import { prisma, testConnection, redis } from '@kael/storage';
import { OpenClaw, type LLMConfig, type Message, type ToolCall } from './openclaw.js';
import { toolsRegistry, getTool } from './toolsRegistry.js';
import { SYSTEM_PROMPT, createKaelAgent } from './kaelAgent.js';
import type { ToolExecutionStep } from '../tools/types.js';

/**
 * Runtime Configuration
 */
export interface RuntimeConfig {
  maxStepsPerCycle: number;
  cycleIntervalMs: number;
  llm: LLMConfig;
  enableTracing: boolean;
  autoGenerateDigests: boolean;
}

/**
 * Runtime State
 */
export interface RuntimeState {
  running: boolean;
  currentCycle: number;
  lastRunAt: Date | null;
  consecutiveErrors: number;
  reasoningTrail: ToolExecutionStep[];
}

/**
 * Load runtime configuration
 */
export function loadRuntimeConfig(): RuntimeConfig {
  return {
    maxStepsPerCycle: parseInt(process.env.MAX_STEPS_PER_CYCLE || '10', 10),
    cycleIntervalMs: parseInt(process.env.CYCLE_INTERVAL_MS || '60000', 10),
    llm: {
      provider: (process.env.MODEL_PROVIDER || 'openai') as LLMConfig['provider'],
      model: process.env.MODEL_NAME || 'gpt-4',
      apiKey: process.env.API_KEY || '',
      baseUrl: process.env.MODEL_BASE_URL,
      temperature: parseFloat(process.env.MODEL_TEMPERATURE || '0.7'),
      maxTokens: parseInt(process.env.MODEL_MAX_TOKENS || '2000', 10),
    },
    enableTracing: process.env.ENABLE_TRACING === 'true',
    autoGenerateDigests: process.env.AUTO_GENERATE_DIGESTS !== 'false',
  };
}

/**
 * Create tool definitions for LLM
 */
function createToolDefinitions(): Array<{
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
  };
}> {
  return toolsRegistry.map((tool) => ({
    type: 'function' as const,
    function: {
      name: tool.name,
      description: tool.description,
      parameters: zodToJsonSchema(tool.inputSchema),
    },
  }));
}

/**
 * Convert Zod schema to JSON Schema
 */
function zodToJsonSchema(schema: z.ZodTypeAny): Record<string, unknown> {
  if (schema instanceof z.ZodObject) {
    const shape = schema.shape as Record<string, z.ZodTypeAny>;
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const [key, value] of Object.entries(shape)) {
      properties[key] = zodTypeToJsonType(value);
      if (!(value instanceof z.ZodOptional)) {
        required.push(key);
      }
    }

    return { type: 'object', properties, required };
  }
  return { type: 'object', properties: {} };
}

function zodTypeToJsonType(zodType: z.ZodTypeAny): Record<string, unknown> {
  if (zodType instanceof z.ZodString) return { type: 'string' };
  if (zodType instanceof z.ZodNumber) return { type: 'number' };
  if (zodType instanceof z.ZodBoolean) return { type: 'boolean' };
  if (zodType instanceof z.ZodArray) {
    return { type: 'array', items: zodTypeToJsonType(zodType.element) };
  }
  if (zodType instanceof z.ZodOptional) return zodTypeToJsonType(zodType.unwrap());
  if (zodType instanceof z.ZodEnum) return { type: 'string', enum: zodType.options };
  return { type: 'string' };
}

/**
 * Kael Agent Runtime
 */
export class KaelRuntime {
  private config: RuntimeConfig;
  private state: RuntimeState;
  private openclaw: OpenClaw;
  private intervalId: NodeJS.Timeout | null = null;

  constructor(config?: Partial<RuntimeConfig>) {
    this.config = { ...loadRuntimeConfig(), ...config };
    this.state = {
      running: false,
      currentCycle: 0,
      lastRunAt: null,
      consecutiveErrors: 0,
      reasoningTrail: [],
    };

    this.openclaw = new OpenClaw(this.config.llm);
    createKaelAgent({ maxIterations: this.config.maxStepsPerCycle, autoRecordSteps: true });

    logger.info('Kael Runtime initialized', {
      maxStepsPerCycle: this.config.maxStepsPerCycle,
      cycleIntervalMs: this.config.cycleIntervalMs,
      llmProvider: this.config.llm.provider,
      llmModel: this.config.llm.model,
    });
  }

  /**
   * Initialize runtime - check connections
   */
  async initialize(): Promise<boolean> {
    try {
      logger.info('Initializing Kael Runtime');

      const dbHealthy = await testConnection();
      if (!dbHealthy) {
        logger.error('Database connection failed');
        return false;
      }

      const redisHealthy = await redis.ping() === 'PONG';
      if (!redisHealthy) {
        logger.error('Redis connection failed');
        return false;
      }

      logger.info('Runtime initialized successfully');
      return true;
    } catch (error) {
      logger.error('Runtime initialization failed', { error });
      return false;
    }
  }

  /**
   * Run a single cycle
   */
  async runOnce(): Promise<{
    success: boolean;
    steps: number;
    actions: string[];
    error?: string;
  }> {
    if (!this.state.running) {
      this.state.running = true;
    }

    this.state.currentCycle++;
    logger.info(`Starting cycle ${this.state.currentCycle}`);

    const actions: string[] = [];
    const cycleStartTime = Date.now();

    try {
      // Step 1: Evaluate system state
      const systemState = await this.evaluateSystemState();
      logger.debug('System state evaluated', systemState);

      // Step 2: Build context for LLM
      const context = this.buildContext(systemState);

      // Step 3: Planning loop
      for (let step = 0; step < this.config.maxStepsPerCycle; step++) {
        logger.debug(`Planning step ${step + 1}/${this.config.maxStepsPerCycle}`);

        const toolCall = await this.chooseNextTool(context);
        if (!toolCall) {
          logger.info('No more actions needed, cycle complete');
          break;
        }

        const result = await this.executeTool(toolCall);
        actions.push(`${toolCall.function.name}: ${result.success ? 'success' : 'failed'}`);
        this.logReasoningStep(toolCall, result);

        if (!result.success && step === 0) {
          throw new Error(`Critical tool failure: ${result.error}`);
        }

        context.push({
          role: 'tool',
          content: JSON.stringify(result.output),
          tool_call_id: toolCall.id,
        });

        if (await this.evaluateGoalAchieved(context)) {
          logger.info('Goal achieved, ending cycle early');
          break;
        }
      }

      // Generate digest if enabled
      if (this.config.autoGenerateDigests) {
        try {
          const { generateAndStoreDigest } = await import('../digest.js');
          const digest = await generateAndStoreDigest(24);
          if (digest.signalCount > 0) {
            actions.push(`generateDigest: ${digest.signalCount} signals`);
          }
        } catch (e) {
          logger.warn('Digest generation failed', { error: e });
        }
      }

      this.state.lastRunAt = new Date();
      this.state.consecutiveErrors = 0;

      const durationMs = Date.now() - cycleStartTime;
      logger.info(`Cycle ${this.state.currentCycle} complete`, { steps: actions.length, durationMs });

      return { success: true, steps: actions.length, actions };
    } catch (error) {
      this.state.consecutiveErrors++;
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      logger.error(`Cycle ${this.state.currentCycle} failed`, { error: errorMsg });
      return { success: false, steps: actions.length, actions, error: errorMsg };
    }
  }

  /**
   * Run continuously
   */
  async runContinuous(): Promise<void> {
    if (this.state.running) {
      logger.warn('Runtime is already running');
      return;
    }

    const initialized = await this.initialize();
    if (!initialized) {
      throw new Error('Runtime initialization failed');
    }

    this.state.running = true;
    logger.info('Starting continuous runtime', { intervalMs: this.config.cycleIntervalMs });

    await this.runOnce();

    this.intervalId = setInterval(async () => {
      if (!this.state.running) return;

      if (this.state.consecutiveErrors >= 5) {
        logger.error('Too many consecutive errors, stopping runtime');
        this.stop();
        return;
      }

      await this.runOnce();
    }, this.config.cycleIntervalMs);

    return new Promise((resolve) => {
      const checkInterval = setInterval(() => {
        if (!this.state.running) {
          clearInterval(checkInterval);
          resolve();
        }
      }, 1000);
    });
  }

  /**
   * Stop the runtime
   */
  stop(): void {
    logger.info('Stopping Kael Runtime');
    this.state.running = false;
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }

  /**
   * Evaluate current system state
   */
  private async evaluateSystemState(): Promise<{
    sourceCount: number;
    enabledSourceCount: number;
    pendingItemCount: number;
    recentSignalCount: number;
    lastDigestAt: Date | null;
  }> {
    const [sourceCount, enabledSourceCount, pendingItemCount] = await Promise.all([
      prisma.source.count(),
      prisma.source.count({ where: { enabled: true } }),
      prisma.rawItem.count({ where: { status: 'pending' } }),
    ]);

    const last24h = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recentSignalCount = await prisma.signal.count({
      where: { createdAt: { gte: last24h } },
    });

    const lastDigest = await prisma.digest.findFirst({
      orderBy: { createdAt: 'desc' },
      select: { createdAt: true },
    });

    return {
      sourceCount,
      enabledSourceCount,
      pendingItemCount,
      recentSignalCount,
      lastDigestAt: lastDigest?.createdAt || null,
    };
  }

  /**
   * Build context for LLM
   */
  private buildContext(systemState: ReturnType<typeof this.evaluateSystemState> extends Promise<infer T> ? T : never): Message[] {
    const state = systemState;
    return [
      { role: 'system', content: SYSTEM_PROMPT },
      {
        role: 'user',
        content: `Current system state:
- Total sources: ${state.sourceCount} (${state.enabledSourceCount} enabled)
- Pending items to analyze: ${state.pendingItemCount}
- Signals created (24h): ${state.recentSignalCount}
- Last digest: ${state.lastDigestAt ? state.lastDigestAt.toISOString() : 'Never'}

What should be the next action to progress toward the goal of maintaining civic intelligence?`,
      },
    ];
  }

  /**
   * Choose next tool using LLM
   */
  private async chooseNextTool(context: Message[]): Promise<ToolCall | null> {
    try {
      const tools = createToolDefinitions();
      const response = await this.openclaw.complete(context, tools);

      if (response.toolCalls && response.toolCalls.length > 0) {
        return response.toolCalls[0];
      }

      if (response.content?.toLowerCase().includes('complete') ||
          response.content?.toLowerCase().includes('done')) {
        return null;
      }

      return {
        id: `call_${Date.now()}`,
        type: 'function',
        function: {
          name: 'listSources',
          arguments: JSON.stringify({ enabledOnly: true, limit: 10 }),
        },
      };
    } catch (error) {
      logger.error('Tool selection failed', { error });
      return null;
    }
  }

  /**
   * Execute a tool
   */
  private async executeTool(toolCall: ToolCall): Promise<{
    success: boolean;
    output: unknown;
    error?: string;
  }> {
    const toolName = toolCall.function.name;
    const toolInput = JSON.parse(toolCall.function.arguments);

    logger.debug(`Executing tool: ${toolName}`, { input: toolInput });

    try {
      const tool = getTool(toolName);
      if (!tool) {
        throw new Error(`Tool not found: ${toolName}`);
      }
      const output = await tool.execute(toolInput);
      return { success: true, output };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      logger.error(`Tool execution failed: ${toolName}`, { error: errorMsg });
      return { success: false, output: null, error: errorMsg };
    }
  }

  /**
   * Log reasoning step
   */
  private logReasoningStep(toolCall: ToolCall, result: { success: boolean; output: unknown }): void {
    const step: ToolExecutionStep = {
      type: 'tool_call',
      toolName: toolCall.function.name,
      input: JSON.parse(toolCall.function.arguments),
      output: result.output,
      durationMs: 0,
      success: result.success,
      timestamp: new Date(),
    };
    this.state.reasoningTrail.push(step);
    if (this.config.enableTracing) {
      logger.debug('Reasoning step logged', { tool: step.toolName, success: step.success });
    }
  }

  /**
   * Evaluate if goal is achieved
   */
  private async evaluateGoalAchieved(_context: Message[]): Promise<boolean> {
    const pendingItems = await prisma.rawItem.count({ where: { status: 'pending' } });
    if (pendingItems === 0 && this.state.reasoningTrail.length > 0) {
      return true;
    }
    return false;
  }

  /**
   * Get runtime state
   */
  getState(): Readonly<RuntimeState> {
    return { ...this.state };
  }

  /**
   * Get reasoning trail
   */
  getReasoningTrail(): Readonly<ToolExecutionStep[]> {
    return [...this.state.reasoningTrail];
  }
}

/**
 * Create and configure a Kael Runtime instance
 */
export function createKaelRuntime(config?: Partial<RuntimeConfig>): KaelRuntime {
  return new KaelRuntime(config);
}

/**
 * Run Kael once (convenience function)
 */
export async function runKaelOnce(config?: Partial<RuntimeConfig>): Promise<{
  success: boolean;
  steps: number;
  actions: string[];
}> {
  const runtime = createKaelRuntime(config);
  const initialized = await runtime.initialize();

  if (!initialized) {
    return { success: false, steps: 0, actions: [] };
  }

  return runtime.runOnce();
}

/**
 * Run Kael continuously (convenience function)
 */
export async function runKaelContinuous(config?: Partial<RuntimeConfig>): Promise<void> {
  const runtime = createKaelRuntime(config);
  return runtime.runContinuous();
}
